### ISSUE TITLE
Notice: http\Client::enqueue(): Could not set option expect_100_timeout (No error)

### ISSUE THREAD

**Issue by jonsuh** [mcdado/unsplash-dl#2]
Getting an error:

`Notice: http\Client::enqueue(): Could not set option expect_100_timeout (No error)`

Seems to be happening at `$request = new http\Client\Request('GET', $this->feed,`. Tried setting a timeout but still fails. Any insight?

**Comment by mcdado** [comment]
Oh hi! didn't see this Issue before.
Well, sorry about the situation, but the script isn't working anymore because it's using an older version of Tumblr's API to get the real full resolution. If you want you could use [this script](https://github.com/mcdado/TumblrPhotoFetch) that is a generalised Tumblr crawler and point it to unsplash.com.
